name: Check code coverage on main-backend

on:
  workflow_call:
    inputs:
      backend-working-directory:
        description: "The path of the backend"
        required: true
        type: string

env:
  CODE_COVERAGE_MODIFIER: 2
  RAMPING_CODE_COVERAGE_CAP: 90

jobs:
  check-code-coverage-on-main-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.backend-working-directory }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
