name: Check code coverage on customers ui

on:
  pull_request:
    # branches:
    #   - main
    paths:
      - 'frontend/customers-ui/**'
  workflow_dispatch:

jobs:
  check-code-coverage-on-customers-ui:
    uses: ./.github/workflows/check-ui-code-coverage.yaml
    with:
      ui-working-directory: 'frontend/customers-ui'
