name: Check code coverage on main backend

on:
  pull_request:
    branches:
      - main-danny
    paths:
      - "backend/main-backend/**"
  workflow_dispatch:

env:
  CODE_COVERAGE_MODIFIER: 2
  RAMPING_CODE_COVERAGE_CAP: 90

jobs:
  check-code-coverage-on-main-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/main-backend
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "21"
      - name: Build with Maven
        run: mvn clean verify

      - name: Jacoco Code Coverage
        run: mvn jacoco:report

      - name: Check Coverage
        run: bash backend/main-backend/check_coverage.sh

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/site/jacoco/
