name: Check quality on competition ui

on:
  pull_request:
    # branches:
    #   - main
    paths:
      - 'frontend/competition-ui/**'
  workflow_dispatch:

jobs:
  codeql-competition-ui:
    uses: ./.github/workflows/codeql-frontend.yml
    with:
      ui-working-directory: 'frontend/competition-ui'
  check-npm-quality-on-competition-ui:
    uses: ./.github/workflows/npm-quality-check.yaml
    with:
      ui-working-directory: 'frontend/competition-ui'
