name: Check code coverage on main ui

on:
  pull_request:
    # branches:
    #   - main

    paths:
      - 'frontend/main-ui/**'
  workflow_dispatch:

jobs:
  check-code-coverage-on-main-ui:
    uses: ./.github/workflows/npm-quality-check.yaml
    with:
      ui-working-directory: 'frontend/main-ui'
