name: Check code quality on notification-backend

on:
  pull_request:
    branches:
      - main

    paths:
      - "backend/notification-backend/**"
  workflow_dispatch:

jobs:
  codeql-notification-backend:
    uses: ./.github/workflows/codeql-backend.yml
    with:
      backend-working-directory: 'backend/notification-backend'
  check-code-coverage-on-notification-backend:
    uses: ./.github/workflows/backend-quality-check.yaml
    with:
      backend-working-directory: 'backend/notification-backend'
