name: Push Updated Jest Config

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  push-to-main:
    # if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: List all artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const artifacts = await github.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log("List of Artifacts:");
            for (const artifact of artifacts.data.artifacts) {
              console.log(`- ${artifact.name} (ID: ${artifact.id}, Size: ${artifact.size_in_bytes} bytes, Created at: ${artifact.created_at})`);
            }

      # - name: Download artifact
      #   uses: actions/download-artifact@v4
      # with:
      # name: updated-jest-config
      # path: .

      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'

      # - name: Commit and push updated jest.config.json
      #   run: |
      #     git config --global user.name 'BrandonWong22'
      #     git config --global user.email 'brandonwong2608@gmail.com'
      #     git checkout main
      #     git pull origin main
      #     git add .
      #     git commit -m "Update coverage threshold"
      #     git push origin main
