name: Push Updated Jest Config

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  push-to-main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Get PR Comments
        id: get_pr_comments
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.issue.number;
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });

            return comments.data.map(comment => comment.body);

      - name: Output PR Comments
        run: echo "${{ steps.get_pr_comments.outputs.result }}"

      # - name: Download artifact
      #   id: download-artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: updated-jest-config
      #     github-token: ${{ github.token }}
      # name:: code-coverage.yaml
      # pr: ${{github.event.pull_request.number}}

      # - name: Get user ID of the person who merged the PR
      #   run: |
      #     echo "The run ID: ${{ github.run_id }}"

      # - name: Download artifact
      #   run: |
      #     echo "Run id ${{ github.event.workflow_run.id }}"
      # uses: actions/download-artifact@v4
      #   with:
      #     name: updated-jest-config
      #     github-token: ${{ github.token }}
      #     repository: ${{ github.repository }}
      #     run-id: ${{ github.event.workflow_run.id }}

      # - name: Configure Git
      #   run: |
      #     git config user.name "BrandonWong22"
      #     git config user.email "brandonwong2608@gmail.com"

      # - name: Commit and push updated jest.config.json
      #   run: |
      #     git add .
      #     git commit -m "Update jest.config.json with new coverage threshold"
      #     git pull origin main --rebase
      #     git push origin HEAD:main
