name: Push Updated Jest Config

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  push-to-main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ github.token }}
          workflow: code-coverage.yaml
          pr: ${{github.event.pull_request.number}}

      - name: Log jest.config.json content
        run: |
          # Make sure to specify the path to the file if it's inside a directory
          FILE_PATH="jest.config.json"

          if [ -f "$FILE_PATH" ]; then
            echo "Contents of $FILE_PATH:"
            cat "$FILE_PATH"
          else
            echo "$FILE_PATH not found!"
          fi

      # - name: Get user ID of the person who merged the PR
      #   run: |
      #     echo "The run ID: ${{ github.run_id }}"

      # - name: Download artifact
      #   run: |
      #     echo "Run id ${{ github.event.workflow_run.id }}"
      # uses: actions/download-artifact@v4
      #   with:
      #     name: updated-jest-config
      #     github-token: ${{ github.token }}
      #     repository: ${{ github.repository }}
      #     run-id: ${{ github.event.workflow_run.id }}

      # - name: Configure Git
      #   run: |
      #     git config user.name "BrandonWong22"
      #     git config user.email "brandonwong2608@gmail.com"

      # - name: Commit and push updated jest.config.json
      #   run: |
      #     git add .
      #     git commit -m "Update jest.config.json with new coverage threshold"
      #     git pull origin main --rebase
      #     git push origin HEAD:main
