name: Push Updated Jest Config to main ui

on:
  pull_request:
    types:
      - closed
    paths:
      - "backend/main-backend/**"
  workflow_dispatch:

jobs:
  push-updated-coverage-threshold-to-main-ui:
    uses: ./.github/workflows/update-backend-code-coverage.yaml
    with:
      backend-working-directory: "backend/main-backend"
