name: Download Artifact on PR Merge

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  download-artifact:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the run ID of the PR workflow
        id: get_run_id
        run: |
          pr_number=${{ github.event.pull_request.number }}
          run_id=$(gh api "repos/${{ github.repository }}/actions/runs" -q ".workflow_runs[] | select(.event == \"pull_request\" and .head_branch == \"${{ github.event.pull_request.head.ref }}\") | .id" | head -n 1)
          echo "run_id=$run_id" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: updated-jest-config
          run-id: ${{ env.run_id }}
